### ISSUE TITLE
原版数据一直停留在0.F稳定版，没有跟随实验版更新

### ISSUE THREAD

**Issue by waveyl** [Aloxaf/cdda-itembrowser#14]
cdda.aloxaf.cn只追踪了kenan包的更新，没追踪原版更新，cdda-trunk.aloxaf.cn/则一直没有更新。

另外导航栏的“0.F”和“实验版”好像标反了
![Screenshot_20211003_110457_mark via](https://user-images.githubusercontent.com/22638873/135737941-59fc6073-21ec-436d-b44b-0d80160265d4.png)
这是“实验版”指向的cdda-trunk.aloxaf.cn
![Screenshot_20211003_110537_mark via](https://user-images.githubusercontent.com/22638873/135737952-671b220d-6e39-4d30-a08d-946f4c5ccd0a.png)
这是“0.F”指向的cdda.aloxaf.cn

**Comment by Aloxaf** [comment]
cdda.aloxaf.cn 只会停留在稳定版
cdda-trunk.aloxaf.cn 修了下，恢复了（大概，两个月过去了也不造官方改成啥样了）（话说竟然已经挂了这么久了

**Comment by waveyl** [comment]
> cdda.aloxaf.cn 只会停留在稳定版 cdda-trunk.aloxaf.cn 修了下，恢复了（大概，两个月过去了也不造官方改成啥样了）（话说竟然已经挂了这么久了

但是kenan包是跟着实验版更新的，如果使用kenan包的话就需要在两个网站来回切换，一个网站查实验版内容，另一个网站查kenan包（所以能不能把两个网站来自官方的数据交换一下。。

**Comment by uiosun** [comment]
> cdda.aloxaf.cn 只会停留在稳定版 cdda-trunk.aloxaf.cn 修了下，恢复了（大概，两个月过去了也不造官方改成啥样了）（话说竟然已经挂了这么久了

网站又挂啦
