### ISSUE TITLE
请求适配新版嵌套容器

### ISSUE THREAD

**Issue by waveyl** [Aloxaf/cdda-itembrowser#15]
cdda更改了容器机制，导致物品浏览器上所有容积显示为0

**Comment by Aloxaf** [comment]
现在才看到……最近发现好多 repo 变成了 unwatch 状态，隔了好几周才发现挂着一个 issue……

**Comment by Aloxaf** [comment]
Fixed in https://github.com/Aloxaf/cdda-itembrowser/commit/96bee112c8f799eacb33ded6a22e5b9e80219e30
