### ISSUE TITLE
【一揽子建议】物品篇之装甲类

### ISSUE THREAD

**Issue by chuanyueyouxia** [Aloxaf/cdda-itembrowser#6]
物品篇之装甲类
-------------
- [x] 1、动力装甲类建议引入```"power_armor": true``` 等判断是否动力甲
- [x] 2、犬具、马甲等动物装甲可以在根据json数据，添加更详实的资料如storage、min_pet_vol、max_pet_vol、pet_bodytype，environmental_protection，结合材质与material_thickness计算装甲防护。
有关代码：
```
"type" : "TOOL",      // Or any other item type
...                   // same entries as for the type (e.g. same entries as for any tool),
"pet_armor_data" : {      // additionally the same armor data like above
    "storage" : 0,
    "environmental_protection" : 0,
    "pet_bodytype": "dog",
    "max_pet_vol": "35000 ml",
    "min_pet_vol": "25000 ml",
    "material_thickness" : 1,
    "power_armor" : false
}
```

**Comment by Aloxaf** [comment]
关于第一点，这个从名称上就看得出来吧……

**Comment by chuanyueyouxia** [comment]
> 关于第一点，这个从名称上就看得出来吧……

也好。无论是浩劫余生还是内置自带mod，都可以看出来

**Comment by chuanyueyouxia** [comment]
另外，物品查看json里"repo_id"是什么？

**Comment by Aloxaf** [comment]
啊，因为我并没有直接保存 JSON，这个查看 JSON 的数据是直接从内存里 dump 出来的
所以还带了一点其它玩意儿……

**Comment by Aloxaf** [comment]
这个 ID 是物品在数据库内部的 ID，因为不同 MOD 可能包含相同 ID 的物品，需要一个独立的 ID 来区分它们……
