### ISSUE TITLE
支持第三方Mod

### ISSUE THREAD

**Issue by linonetwo** [Aloxaf/cdda-itembrowser#9]
Hi，我们最近在翻译 Kenan Mod Pack，感觉翻译起来吃力打算搞一个文档站点，要怎么复用这个的代码来加载第三方mod呢？

还有能不能让现在的网站支持 Kenan Mod Pack 呢？这样就不用搞两个分开的站点了，我感觉 Kenan Mod Pack 之后用的人应该会挺多，包含奥术 PK Sec 等mod的。

**Comment by Aloxaf** [comment]
> Hi，我们最近在翻译 Kenan Mod Pack，感觉翻译起来吃力打算搞一个文档站点，要怎么复用这个的代码来加载第三方mod呢？

按照 Dockerfile 里的步骤就行了，把第三方 MOD 和官方 MOD 放在一起即可。
 
> 还有能不能让现在的网站支持 Kenan Mod Pack 呢？这样就不用搞两个分开的站点了，我感觉 Kenan Mod Pack 之后用的人应该会挺多，包含奥术 PK Sec 等mod的。

我确实有加入 MOD 的计划，但是实验版变动比较频繁，MOD 不一定能兼容。

我计划在 0.F 稳定之后单独维护一个稳定版的站点，到时就可以添加各种 MOD。不过现在基本上也不会有太大变动，也可以开始加 MOD 了。

你愿意的话可以提供一个固定的下载地址（比如 GitHub repo），我修改一下脚本每日从那里拉取更新。

**Comment by linonetwo** [comment]
可以用这个地址 https://github.com/linonetwo/CDDA-Kenan-Modpack-Chinese

**Comment by Aloxaf** [comment]
试了下，MOD 太多感觉有点杂，对于不打 MOD 的用户来说不是很友好，我看什么时候先把 #5 完成。
